//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCene.Model.PIN_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.b2b.navigator.rs/", ConfigurationName="PIN_ServiceReference.StockWebservice")]
    public interface StockWebservice {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(group))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebCene.Model.PIN_ServiceReference.getItemImageResponse getItemImage(WebCene.Model.PIN_ServiceReference.getItemImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getItemImageResponse> getItemImageAsync(WebCene.Model.PIN_ServiceReference.getItemImageRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(group))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebCene.Model.PIN_ServiceReference.getStockAvailabilityResponse getStockAvailability(WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getStockAvailabilityResponse> getStockAvailabilityAsync(WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(group))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebCene.Model.PIN_ServiceReference.getItemPricesResponse getItemPrices(WebCene.Model.PIN_ServiceReference.getItemPricesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getItemPricesResponse> getItemPricesAsync(WebCene.Model.PIN_ServiceReference.getItemPricesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(group))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebCene.Model.PIN_ServiceReference.getAllItemsResponse getAllItems(WebCene.Model.PIN_ServiceReference.getAllItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getAllItemsResponse> getAllItemsAsync(WebCene.Model.PIN_ServiceReference.getAllItemsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(group))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesResponse getAllItemsWithQuantities(WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesResponse> getAllItemsWithQuantitiesAsync(WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class b2BWebServiceDAO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stockItemImageDAO item_imageField;
        
        private item[] itemField;
        
        private stockItemPriceDAO[] price_itemField;
        
        private stockItemSimpleDAO[] stock_itemField;
        
        private stockItemQuantityDAO[] stock_item_quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public stockItemImageDAO item_image {
            get {
                return this.item_imageField;
            }
            set {
                this.item_imageField = value;
                this.RaisePropertyChanged("item_image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public item[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("price_item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public stockItemPriceDAO[] price_item {
            get {
                return this.price_itemField;
            }
            set {
                this.price_itemField = value;
                this.RaisePropertyChanged("price_item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stock_item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public stockItemSimpleDAO[] stock_item {
            get {
                return this.stock_itemField;
            }
            set {
                this.stock_itemField = value;
                this.RaisePropertyChanged("stock_item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stock_item_quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public stockItemQuantityDAO[] stock_item_quantity {
            get {
                return this.stock_item_quantityField;
            }
            set {
                this.stock_item_quantityField = value;
                this.RaisePropertyChanged("stock_item_quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class stockItemImageDAO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] item_imageField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] item_image {
            get {
                return this.item_imageField;
            }
            set {
                this.item_imageField = value;
                this.RaisePropertyChanged("item_image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class stockItemQuantityDAO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string item_codeField;
        
        private double quantityField;
        
        private bool quantityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string item_code {
            get {
                return this.item_codeField;
            }
            set {
                this.item_codeField = value;
                this.RaisePropertyChanged("item_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class stockItemSimpleDAO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private bool on_stockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool on_stock {
            get {
                return this.on_stockField;
            }
            set {
                this.on_stockField = value;
                this.RaisePropertyChanged("on_stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class stockItemPriceDAO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private double price_with_discountsField;
        
        private bool price_with_discountsFieldSpecified;
        
        private double retail_priceField;
        
        private bool retail_priceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double price_with_discounts {
            get {
                return this.price_with_discountsField;
            }
            set {
                this.price_with_discountsField = value;
                this.RaisePropertyChanged("price_with_discounts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_with_discountsSpecified {
            get {
                return this.price_with_discountsFieldSpecified;
            }
            set {
                this.price_with_discountsFieldSpecified = value;
                this.RaisePropertyChanged("price_with_discountsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double retail_price {
            get {
                return this.retail_priceField;
            }
            set {
                this.retail_priceField = value;
                this.RaisePropertyChanged("retail_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retail_priceSpecified {
            get {
                return this.retail_priceFieldSpecified;
            }
            set {
                this.retail_priceFieldSpecified = value;
                this.RaisePropertyChanged("retail_priceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class manufacturer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(item_group))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public abstract partial class group : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private int order_numField;
        
        private bool order_numFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int order_num {
            get {
                return this.order_numField;
            }
            set {
                this.order_numField = value;
                this.RaisePropertyChanged("order_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool order_numSpecified {
            get {
                return this.order_numFieldSpecified;
            }
            set {
                this.order_numFieldSpecified = value;
                this.RaisePropertyChanged("order_numSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class item_group : group {
        
        private item_group parent_groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public item_group parent_group {
            get {
                return this.parent_groupField;
            }
            set {
                this.parent_groupField = value;
                this.RaisePropertyChanged("parent_group");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class attribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private bool selectedField;
        
        private bool selectedFieldSpecified;
        
        private string erp_codeField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private attributeType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("selected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selectedSpecified {
            get {
                return this.selectedFieldSpecified;
            }
            set {
                this.selectedFieldSpecified = value;
                this.RaisePropertyChanged("selectedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erp_code {
            get {
                return this.erp_codeField;
            }
            set {
                this.erp_codeField = value;
                this.RaisePropertyChanged("erp_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public attributeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public enum attributeType {
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        NUMERIC,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        LINK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class attribute_value : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attribute attributeField;
        
        private string valueField;
        
        private string erp_codeField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public attribute attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("attribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string erp_code {
            get {
                return this.erp_codeField;
            }
            set {
                this.erp_codeField = value;
                this.RaisePropertyChanged("erp_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.b2b.navigator.rs/")]
    public partial class item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attribute_value[] attribute_valueField;
        
        private string descriptionField;
        
        private string eanField;
        
        private string erp_codeField;
        
        private string item_codeField;
        
        private item_group item_groupField;
        
        private manufacturer manufacturerField;
        
        private string nameField;
        
        private string oemField;
        
        private double stockField;
        
        private bool stockFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private bool on_stockField;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private double price_with_discountsField;
        
        private bool price_with_discountsFieldSpecified;
        
        private double retail_priceField;
        
        private bool retail_priceFieldSpecified;
        
        private double tax_valueField;
        
        private int warrantyField;
        
        private bool warrantyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute_value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public attribute_value[] attribute_value {
            get {
                return this.attribute_valueField;
            }
            set {
                this.attribute_valueField = value;
                this.RaisePropertyChanged("attribute_value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ean {
            get {
                return this.eanField;
            }
            set {
                this.eanField = value;
                this.RaisePropertyChanged("ean");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string erp_code {
            get {
                return this.erp_codeField;
            }
            set {
                this.erp_codeField = value;
                this.RaisePropertyChanged("erp_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string item_code {
            get {
                return this.item_codeField;
            }
            set {
                this.item_codeField = value;
                this.RaisePropertyChanged("item_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public item_group item_group {
            get {
                return this.item_groupField;
            }
            set {
                this.item_groupField = value;
                this.RaisePropertyChanged("item_group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public manufacturer manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string oem {
            get {
                return this.oemField;
            }
            set {
                this.oemField = value;
                this.RaisePropertyChanged("oem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockSpecified {
            get {
                return this.stockFieldSpecified;
            }
            set {
                this.stockFieldSpecified = value;
                this.RaisePropertyChanged("stockSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool on_stock {
            get {
                return this.on_stockField;
            }
            set {
                this.on_stockField = value;
                this.RaisePropertyChanged("on_stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double price_with_discounts {
            get {
                return this.price_with_discountsField;
            }
            set {
                this.price_with_discountsField = value;
                this.RaisePropertyChanged("price_with_discounts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_with_discountsSpecified {
            get {
                return this.price_with_discountsFieldSpecified;
            }
            set {
                this.price_with_discountsFieldSpecified = value;
                this.RaisePropertyChanged("price_with_discountsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double retail_price {
            get {
                return this.retail_priceField;
            }
            set {
                this.retail_priceField = value;
                this.RaisePropertyChanged("retail_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retail_priceSpecified {
            get {
                return this.retail_priceFieldSpecified;
            }
            set {
                this.retail_priceFieldSpecified = value;
                this.RaisePropertyChanged("retail_priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double tax_value {
            get {
                return this.tax_valueField;
            }
            set {
                this.tax_valueField = value;
                this.RaisePropertyChanged("tax_value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
                this.RaisePropertyChanged("warranty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool warrantySpecified {
            get {
                return this.warrantyFieldSpecified;
            }
            set {
                this.warrantyFieldSpecified = value;
                this.RaisePropertyChanged("warrantySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemImage", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getItemImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        public getItemImageRequest() {
        }
        
        public getItemImageRequest(long arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemImageResponse", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getItemImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return;
        
        public getItemImageResponse() {
        }
        
        public getItemImageResponse(WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockAvailability", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getStockAvailabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long shopId;
        
        public getStockAvailabilityRequest() {
        }
        
        public getStockAvailabilityRequest(string guid, long shopId) {
            this.guid = guid;
            this.shopId = shopId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockAvailabilityResponse", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getStockAvailabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return;
        
        public getStockAvailabilityResponse() {
        }
        
        public getStockAvailabilityResponse(WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemPrices", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getItemPricesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long shopId;
        
        public getItemPricesRequest() {
        }
        
        public getItemPricesRequest(string guid, long shopId) {
            this.guid = guid;
            this.shopId = shopId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemPricesResponse", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getItemPricesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return;
        
        public getItemPricesResponse() {
        }
        
        public getItemPricesResponse(WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllItems", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getAllItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long shopId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool allItems;
        
        public getAllItemsRequest() {
        }
        
        public getAllItemsRequest(string guid, long shopId, bool allItems) {
            this.guid = guid;
            this.shopId = shopId;
            this.allItems = allItems;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllItemsResponse", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getAllItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return;
        
        public getAllItemsResponse() {
        }
        
        public getAllItemsResponse(WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllItemsWithQuantities", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getAllItemsWithQuantitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long shopId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string warehouseErpCode;
        
        public getAllItemsWithQuantitiesRequest() {
        }
        
        public getAllItemsWithQuantitiesRequest(string guid, long shopId, string warehouseErpCode) {
            this.guid = guid;
            this.shopId = shopId;
            this.warehouseErpCode = warehouseErpCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllItemsWithQuantitiesResponse", WrapperNamespace="http://webservice.b2b.navigator.rs/", IsWrapped=true)]
    public partial class getAllItemsWithQuantitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.b2b.navigator.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return;
        
        public getAllItemsWithQuantitiesResponse() {
        }
        
        public getAllItemsWithQuantitiesResponse(WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockWebserviceChannel : WebCene.Model.PIN_ServiceReference.StockWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockWebserviceClient : System.ServiceModel.ClientBase<WebCene.Model.PIN_ServiceReference.StockWebservice>, WebCene.Model.PIN_ServiceReference.StockWebservice {
        
        public StockWebserviceClient() {
        }
        
        public StockWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.PIN_ServiceReference.getItemImageResponse WebCene.Model.PIN_ServiceReference.StockWebservice.getItemImage(WebCene.Model.PIN_ServiceReference.getItemImageRequest request) {
            return base.Channel.getItemImage(request);
        }
        
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO getItemImage(long arg0, long arg1) {
            WebCene.Model.PIN_ServiceReference.getItemImageRequest inValue = new WebCene.Model.PIN_ServiceReference.getItemImageRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebCene.Model.PIN_ServiceReference.getItemImageResponse retVal = ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getItemImage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getItemImageResponse> WebCene.Model.PIN_ServiceReference.StockWebservice.getItemImageAsync(WebCene.Model.PIN_ServiceReference.getItemImageRequest request) {
            return base.Channel.getItemImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getItemImageResponse> getItemImageAsync(long arg0, long arg1) {
            WebCene.Model.PIN_ServiceReference.getItemImageRequest inValue = new WebCene.Model.PIN_ServiceReference.getItemImageRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getItemImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.PIN_ServiceReference.getStockAvailabilityResponse WebCene.Model.PIN_ServiceReference.StockWebservice.getStockAvailability(WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest request) {
            return base.Channel.getStockAvailability(request);
        }
        
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO getStockAvailability(string guid, long shopId) {
            WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest inValue = new WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            WebCene.Model.PIN_ServiceReference.getStockAvailabilityResponse retVal = ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getStockAvailability(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getStockAvailabilityResponse> WebCene.Model.PIN_ServiceReference.StockWebservice.getStockAvailabilityAsync(WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest request) {
            return base.Channel.getStockAvailabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getStockAvailabilityResponse> getStockAvailabilityAsync(string guid, long shopId) {
            WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest inValue = new WebCene.Model.PIN_ServiceReference.getStockAvailabilityRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            return ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getStockAvailabilityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.PIN_ServiceReference.getItemPricesResponse WebCene.Model.PIN_ServiceReference.StockWebservice.getItemPrices(WebCene.Model.PIN_ServiceReference.getItemPricesRequest request) {
            return base.Channel.getItemPrices(request);
        }
        
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO getItemPrices(string guid, long shopId) {
            WebCene.Model.PIN_ServiceReference.getItemPricesRequest inValue = new WebCene.Model.PIN_ServiceReference.getItemPricesRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            WebCene.Model.PIN_ServiceReference.getItemPricesResponse retVal = ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getItemPrices(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getItemPricesResponse> WebCene.Model.PIN_ServiceReference.StockWebservice.getItemPricesAsync(WebCene.Model.PIN_ServiceReference.getItemPricesRequest request) {
            return base.Channel.getItemPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getItemPricesResponse> getItemPricesAsync(string guid, long shopId) {
            WebCene.Model.PIN_ServiceReference.getItemPricesRequest inValue = new WebCene.Model.PIN_ServiceReference.getItemPricesRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            return ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getItemPricesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.PIN_ServiceReference.getAllItemsResponse WebCene.Model.PIN_ServiceReference.StockWebservice.getAllItems(WebCene.Model.PIN_ServiceReference.getAllItemsRequest request) {
            return base.Channel.getAllItems(request);
        }
        
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO getAllItems(string guid, long shopId, bool allItems) {
            WebCene.Model.PIN_ServiceReference.getAllItemsRequest inValue = new WebCene.Model.PIN_ServiceReference.getAllItemsRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            inValue.allItems = allItems;
            WebCene.Model.PIN_ServiceReference.getAllItemsResponse retVal = ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getAllItems(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getAllItemsResponse> WebCene.Model.PIN_ServiceReference.StockWebservice.getAllItemsAsync(WebCene.Model.PIN_ServiceReference.getAllItemsRequest request) {
            return base.Channel.getAllItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getAllItemsResponse> getAllItemsAsync(string guid, long shopId, bool allItems) {
            WebCene.Model.PIN_ServiceReference.getAllItemsRequest inValue = new WebCene.Model.PIN_ServiceReference.getAllItemsRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            inValue.allItems = allItems;
            return ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getAllItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesResponse WebCene.Model.PIN_ServiceReference.StockWebservice.getAllItemsWithQuantities(WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest request) {
            return base.Channel.getAllItemsWithQuantities(request);
        }
        
        public WebCene.Model.PIN_ServiceReference.b2BWebServiceDAO getAllItemsWithQuantities(string guid, long shopId, string warehouseErpCode) {
            WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest inValue = new WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            inValue.warehouseErpCode = warehouseErpCode;
            WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesResponse retVal = ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getAllItemsWithQuantities(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesResponse> WebCene.Model.PIN_ServiceReference.StockWebservice.getAllItemsWithQuantitiesAsync(WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest request) {
            return base.Channel.getAllItemsWithQuantitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesResponse> getAllItemsWithQuantitiesAsync(string guid, long shopId, string warehouseErpCode) {
            WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest inValue = new WebCene.Model.PIN_ServiceReference.getAllItemsWithQuantitiesRequest();
            inValue.guid = guid;
            inValue.shopId = shopId;
            inValue.warehouseErpCode = warehouseErpCode;
            return ((WebCene.Model.PIN_ServiceReference.StockWebservice)(this)).getAllItemsWithQuantitiesAsync(inValue);
        }
    }
}
