//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCene.Model.CT_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductGroup", Namespace="http://www.ct4partners.com/B2B")]
    [System.SerializableAttribute()]
    public partial class ProductGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCene.Model.CT_ServiceReference.ProductAttribute[] AttributesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GroupDescription {
            get {
                return this.GroupDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupDescriptionField, value) != true)) {
                    this.GroupDescriptionField = value;
                    this.RaisePropertyChanged("GroupDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebCene.Model.CT_ServiceReference.ProductAttribute[] Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductAttribute", Namespace="http://www.ct4partners.com/B2B")]
    [System.SerializableAttribute()]
    public partial class ProductAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AttributeName {
            get {
                return this.AttributeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeNameField, value) != true)) {
                    this.AttributeNameField = value;
                    this.RaisePropertyChanged("AttributeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AttributeValue {
            get {
                return this.AttributeValueField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeValueField, value) != true)) {
                    this.AttributeValueField = value;
                    this.RaisePropertyChanged("AttributeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AttributeCode {
            get {
                return this.AttributeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeCodeField, value) != true)) {
                    this.AttributeCodeField = value;
                    this.RaisePropertyChanged("AttributeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CTPRODUCT", Namespace="http://www.ct4partners.com/B2B")]
    [System.SerializableAttribute()]
    public partial class CTPRODUCT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCTGROUPCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MANUFACTURERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MANUFACTURERCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QTTYINSTOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRICENOTAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RETAILPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SHORT_DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WARRANTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EUR_ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BARCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMAGE_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCene.Model.CT_ServiceReference.ArrayOfString IMAGE_URLSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebCene.Model.CT_ServiceReference.ArrayOfProductAttribute1 ATTRIBUTESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PRODUCTGROUPCODE {
            get {
                return this.PRODUCTGROUPCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTGROUPCODEField, value) != true)) {
                    this.PRODUCTGROUPCODEField = value;
                    this.RaisePropertyChanged("PRODUCTGROUPCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MANUFACTURER {
            get {
                return this.MANUFACTURERField;
            }
            set {
                if ((object.ReferenceEquals(this.MANUFACTURERField, value) != true)) {
                    this.MANUFACTURERField = value;
                    this.RaisePropertyChanged("MANUFACTURER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MANUFACTURERCODE {
            get {
                return this.MANUFACTURERCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.MANUFACTURERCODEField, value) != true)) {
                    this.MANUFACTURERCODEField = value;
                    this.RaisePropertyChanged("MANUFACTURERCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string QTTYINSTOCK {
            get {
                return this.QTTYINSTOCKField;
            }
            set {
                if ((object.ReferenceEquals(this.QTTYINSTOCKField, value) != true)) {
                    this.QTTYINSTOCKField = value;
                    this.RaisePropertyChanged("QTTYINSTOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TAX {
            get {
                return this.TAXField;
            }
            set {
                if ((object.ReferenceEquals(this.TAXField, value) != true)) {
                    this.TAXField = value;
                    this.RaisePropertyChanged("TAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PRICE {
            get {
                return this.PRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRICEField, value) != true)) {
                    this.PRICEField = value;
                    this.RaisePropertyChanged("PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PRICENOTAX {
            get {
                return this.PRICENOTAXField;
            }
            set {
                if ((object.ReferenceEquals(this.PRICENOTAXField, value) != true)) {
                    this.PRICENOTAXField = value;
                    this.RaisePropertyChanged("PRICENOTAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string RETAILPRICE {
            get {
                return this.RETAILPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.RETAILPRICEField, value) != true)) {
                    this.RETAILPRICEField = value;
                    this.RaisePropertyChanged("RETAILPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SHORT_DESCRIPTION {
            get {
                return this.SHORT_DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.SHORT_DESCRIPTIONField, value) != true)) {
                    this.SHORT_DESCRIPTIONField = value;
                    this.RaisePropertyChanged("SHORT_DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string WARRANTY {
            get {
                return this.WARRANTYField;
            }
            set {
                if ((object.ReferenceEquals(this.WARRANTYField, value) != true)) {
                    this.WARRANTYField = value;
                    this.RaisePropertyChanged("WARRANTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string EUR_ExchangeRate {
            get {
                return this.EUR_ExchangeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.EUR_ExchangeRateField, value) != true)) {
                    this.EUR_ExchangeRateField = value;
                    this.RaisePropertyChanged("EUR_ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string BARCODE {
            get {
                return this.BARCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.BARCODEField, value) != true)) {
                    this.BARCODEField = value;
                    this.RaisePropertyChanged("BARCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string IMAGE_URL {
            get {
                return this.IMAGE_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGE_URLField, value) != true)) {
                    this.IMAGE_URLField = value;
                    this.RaisePropertyChanged("IMAGE_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public WebCene.Model.CT_ServiceReference.ArrayOfString IMAGE_URLS {
            get {
                return this.IMAGE_URLSField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGE_URLSField, value) != true)) {
                    this.IMAGE_URLSField = value;
                    this.RaisePropertyChanged("IMAGE_URLS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public WebCene.Model.CT_ServiceReference.ArrayOfProductAttribute1 ATTRIBUTES {
            get {
                return this.ATTRIBUTESField;
            }
            set {
                if ((object.ReferenceEquals(this.ATTRIBUTESField, value) != true)) {
                    this.ATTRIBUTESField = value;
                    this.RaisePropertyChanged("ATTRIBUTES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.ct4partners.com/B2B", ItemName="URL")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProductAttribute1", Namespace="http://www.ct4partners.com/B2B", ItemName="ATTRIBUTE")]
    [System.SerializableAttribute()]
    public class ArrayOfProductAttribute1 : System.Collections.Generic.List<WebCene.Model.CT_ServiceReference.ProductAttribute> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ct4partners.com/B2B", ConfigurationName="CT_ServiceReference.CTProductsInStockSoap")]
    public interface CTProductsInStockSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.ct4partners.com/B2B is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProductGroups", ReplyAction="*")]
        WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponse GetCTProductGroups(WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProductGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponse> GetCTProductGroupsAsync(WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.ct4partners.com/B2B is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProductGroups_WithAttributes", ReplyAction="*")]
        WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponse GetCTProductGroups_WithAttributes(WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProductGroups_WithAttributes", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponse> GetCTProductGroups_WithAttributesAsync(WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.ct4partners.com/B2B is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProducts", ReplyAction="*")]
        WebCene.Model.CT_ServiceReference.GetCTProductsResponse GetCTProducts(WebCene.Model.CT_ServiceReference.GetCTProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductsResponse> GetCTProductsAsync(WebCene.Model.CT_ServiceReference.GetCTProductsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.ct4partners.com/B2B is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProducts_WithAttributes", ReplyAction="*")]
        WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponse GetCTProducts_WithAttributes(WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ct4partners.com/B2B/GetCTProducts_WithAttributes", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponse> GetCTProducts_WithAttributesAsync(WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProductGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProductGroups", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequestBody Body;
        
        public GetCTProductGroupsRequest() {
        }
        
        public GetCTProductGroupsRequest(WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProductGroupsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCTProductGroupsRequestBody() {
        }
        
        public GetCTProductGroupsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProductGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProductGroupsResponse", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponseBody Body;
        
        public GetCTProductGroupsResponse() {
        }
        
        public GetCTProductGroupsResponse(WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProductGroupsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebCene.Model.CT_ServiceReference.ProductGroup[] GetCTProductGroupsResult;
        
        public GetCTProductGroupsResponseBody() {
        }
        
        public GetCTProductGroupsResponseBody(WebCene.Model.CT_ServiceReference.ProductGroup[] GetCTProductGroupsResult) {
            this.GetCTProductGroupsResult = GetCTProductGroupsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProductGroups_WithAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProductGroups_WithAttributes", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequestBody Body;
        
        public GetCTProductGroups_WithAttributesRequest() {
        }
        
        public GetCTProductGroups_WithAttributesRequest(WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProductGroups_WithAttributesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCTProductGroups_WithAttributesRequestBody() {
        }
        
        public GetCTProductGroups_WithAttributesRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProductGroups_WithAttributesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProductGroups_WithAttributesResponse", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponseBody Body;
        
        public GetCTProductGroups_WithAttributesResponse() {
        }
        
        public GetCTProductGroups_WithAttributesResponse(WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProductGroups_WithAttributesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebCene.Model.CT_ServiceReference.ProductGroup[] GetCTProductGroups_WithAttributesResult;
        
        public GetCTProductGroups_WithAttributesResponseBody() {
        }
        
        public GetCTProductGroups_WithAttributesResponseBody(WebCene.Model.CT_ServiceReference.ProductGroup[] GetCTProductGroups_WithAttributesResult) {
            this.GetCTProductGroups_WithAttributesResult = GetCTProductGroups_WithAttributesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProducts", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProductsRequestBody Body;
        
        public GetCTProductsRequest() {
        }
        
        public GetCTProductsRequest(WebCene.Model.CT_ServiceReference.GetCTProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string productGroupCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string manufacturerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string searchphrase;
        
        public GetCTProductsRequestBody() {
        }
        
        public GetCTProductsRequestBody(string username, string password, string productGroupCode, string manufacturerCode, string searchphrase) {
            this.username = username;
            this.password = password;
            this.productGroupCode = productGroupCode;
            this.manufacturerCode = manufacturerCode;
            this.searchphrase = searchphrase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProductsResponse", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProductsResponseBody Body;
        
        public GetCTProductsResponse() {
        }
        
        public GetCTProductsResponse(WebCene.Model.CT_ServiceReference.GetCTProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebCene.Model.CT_ServiceReference.CTPRODUCT[] GetCTProductsResult;
        
        public GetCTProductsResponseBody() {
        }
        
        public GetCTProductsResponseBody(WebCene.Model.CT_ServiceReference.CTPRODUCT[] GetCTProductsResult) {
            this.GetCTProductsResult = GetCTProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProducts_WithAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProducts_WithAttributes", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequestBody Body;
        
        public GetCTProducts_WithAttributesRequest() {
        }
        
        public GetCTProducts_WithAttributesRequest(WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProducts_WithAttributesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string productGroupCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string manufacturerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string searchphrase;
        
        public GetCTProducts_WithAttributesRequestBody() {
        }
        
        public GetCTProducts_WithAttributesRequestBody(string username, string password, string productGroupCode, string manufacturerCode, string searchphrase) {
            this.username = username;
            this.password = password;
            this.productGroupCode = productGroupCode;
            this.manufacturerCode = manufacturerCode;
            this.searchphrase = searchphrase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCTProducts_WithAttributesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCTProducts_WithAttributesResponse", Namespace="http://www.ct4partners.com/B2B", Order=0)]
        public WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponseBody Body;
        
        public GetCTProducts_WithAttributesResponse() {
        }
        
        public GetCTProducts_WithAttributesResponse(WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ct4partners.com/B2B")]
    public partial class GetCTProducts_WithAttributesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebCene.Model.CT_ServiceReference.CTPRODUCT[] GetCTProducts_WithAttributesResult;
        
        public GetCTProducts_WithAttributesResponseBody() {
        }
        
        public GetCTProducts_WithAttributesResponseBody(WebCene.Model.CT_ServiceReference.CTPRODUCT[] GetCTProducts_WithAttributesResult) {
            this.GetCTProducts_WithAttributesResult = GetCTProducts_WithAttributesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CTProductsInStockSoapChannel : WebCene.Model.CT_ServiceReference.CTProductsInStockSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTProductsInStockSoapClient : System.ServiceModel.ClientBase<WebCene.Model.CT_ServiceReference.CTProductsInStockSoap>, WebCene.Model.CT_ServiceReference.CTProductsInStockSoap {
        
        public CTProductsInStockSoapClient() {
        }
        
        public CTProductsInStockSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTProductsInStockSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTProductsInStockSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTProductsInStockSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponse WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProductGroups(WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest request) {
            return base.Channel.GetCTProductGroups(request);
        }
        
        public WebCene.Model.CT_ServiceReference.ProductGroup[] GetCTProductGroups(string username, string password) {
            WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponse retVal = ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProductGroups(inValue);
            return retVal.Body.GetCTProductGroupsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponse> WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProductGroupsAsync(WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest request) {
            return base.Channel.GetCTProductGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductGroupsResponse> GetCTProductGroupsAsync(string username, string password) {
            WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProductGroupsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProductGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponse WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProductGroups_WithAttributes(WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest request) {
            return base.Channel.GetCTProductGroups_WithAttributes(request);
        }
        
        public WebCene.Model.CT_ServiceReference.ProductGroup[] GetCTProductGroups_WithAttributes(string username, string password) {
            WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponse retVal = ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProductGroups_WithAttributes(inValue);
            return retVal.Body.GetCTProductGroups_WithAttributesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponse> WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProductGroups_WithAttributesAsync(WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest request) {
            return base.Channel.GetCTProductGroups_WithAttributesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesResponse> GetCTProductGroups_WithAttributesAsync(string username, string password) {
            WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProductGroups_WithAttributesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProductGroups_WithAttributesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.CT_ServiceReference.GetCTProductsResponse WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProducts(WebCene.Model.CT_ServiceReference.GetCTProductsRequest request) {
            return base.Channel.GetCTProducts(request);
        }
        
        public WebCene.Model.CT_ServiceReference.CTPRODUCT[] GetCTProducts(string username, string password, string productGroupCode, string manufacturerCode, string searchphrase) {
            WebCene.Model.CT_ServiceReference.GetCTProductsRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProductsRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProductsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.productGroupCode = productGroupCode;
            inValue.Body.manufacturerCode = manufacturerCode;
            inValue.Body.searchphrase = searchphrase;
            WebCene.Model.CT_ServiceReference.GetCTProductsResponse retVal = ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProducts(inValue);
            return retVal.Body.GetCTProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductsResponse> WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProductsAsync(WebCene.Model.CT_ServiceReference.GetCTProductsRequest request) {
            return base.Channel.GetCTProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProductsResponse> GetCTProductsAsync(string username, string password, string productGroupCode, string manufacturerCode, string searchphrase) {
            WebCene.Model.CT_ServiceReference.GetCTProductsRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProductsRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProductsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.productGroupCode = productGroupCode;
            inValue.Body.manufacturerCode = manufacturerCode;
            inValue.Body.searchphrase = searchphrase;
            return ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponse WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProducts_WithAttributes(WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest request) {
            return base.Channel.GetCTProducts_WithAttributes(request);
        }
        
        public WebCene.Model.CT_ServiceReference.CTPRODUCT[] GetCTProducts_WithAttributes(string username, string password, string productGroupCode, string manufacturerCode, string searchphrase) {
            WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.productGroupCode = productGroupCode;
            inValue.Body.manufacturerCode = manufacturerCode;
            inValue.Body.searchphrase = searchphrase;
            WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponse retVal = ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProducts_WithAttributes(inValue);
            return retVal.Body.GetCTProducts_WithAttributesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponse> WebCene.Model.CT_ServiceReference.CTProductsInStockSoap.GetCTProducts_WithAttributesAsync(WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest request) {
            return base.Channel.GetCTProducts_WithAttributesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesResponse> GetCTProducts_WithAttributesAsync(string username, string password, string productGroupCode, string manufacturerCode, string searchphrase) {
            WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest inValue = new WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequest();
            inValue.Body = new WebCene.Model.CT_ServiceReference.GetCTProducts_WithAttributesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.productGroupCode = productGroupCode;
            inValue.Body.manufacturerCode = manufacturerCode;
            inValue.Body.searchphrase = searchphrase;
            return ((WebCene.Model.CT_ServiceReference.CTProductsInStockSoap)(this)).GetCTProducts_WithAttributesAsync(inValue);
        }
    }
}
